{
 "title": "Docker Exporter (logporter)",
 "description": "A simple and lightweight alternative to cAdvisor for getting all basic metrics from Docker containers. Source code: https://github.com/Lifailon/logporter",
 "tags": [ "Docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ContainerName",
    "query": {
     "query": "query_result(group by(containerName) (docker_cpu_usage_total))"
    }
   },
   {
    "name": "HostName",
    "query": {
     "query": "query_result(group by(hostname) (docker_cpu_usage_total))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Containers",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - docker_started_time{containerName=~\"$ContainerName\", hostname=~\"$HostName\"}",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_containers_up_count{hostname=~\"$HostName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stopped Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_containers_down_count{hostname=~\"$HostName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Total Usage",
   "type": "timeseries",
   "description": "User + Kernel = Total",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(docker_cpu_usage_total{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "CPU Total Usage",
   "type": "stat",
   "description": "Total memory usage of all containers",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(docker_cpu_usage_total{hostname=~\"$HostName\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Total memory usage of all containers",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_memory_usage{hostname=~\"$HostName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Total network usage of all containers",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(docker_network_received_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(docker_network_transmit_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "stat",
   "description": "Total block storage usage of all containers",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(docker_io_read_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(docker_io_write_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Memory Usage (MByte)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_memory_usage{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Network Received KBytes",
   "type": "timeseries",
   "description": "Input from the network",
   "gridPos": { "h": 14, "w": 7, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_network_received_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "description": "Input from the block storage",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_io_read_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "PIDs Count",
   "type": "timeseries",
   "description": "Processes count",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "docker_process_pids_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Network Transmit KBytes",
   "type": "timeseries",
   "description": "Output to the network",
   "gridPos": { "h": 14, "w": 7, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_network_transmit_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Disk Write KBytes",
   "type": "timeseries",
   "description": "Output to the block storage",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_io_write_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  { "title": "CPU User and Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU User Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(docker_cpu_usage_user{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "CPU Kernel Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(docker_cpu_usage_kernel{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Network Packages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Received Packages",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(docker_network_received_packages{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Network Transmit Packages",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(docker_network_transmit_packages{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Logged Messages Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs Standart Count (stdout)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "round(increase(docker_logs_stdout_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]))",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Logs Error Count (stderr)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "round(increase(docker_logs_stderr_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]))",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Logs All Count",
     "type": "timeseries",
     "description": "stdout + stderr",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "round(increase(docker_logs_all_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]))",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Logs Custom Count",
     "type": "timeseries",
     "description": "Number of errors in logs using a custom query (by default error level in json format)",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "round(increase(docker_logs_custom_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]))",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Hashmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Total Usage",
     "type": "heatmap",
     "description": "User + Kernel = Total",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 319 },
     "targets": [
      {
       "expr": "rate(docker_cpu_usage_total{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "heatmap",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 319 },
     "targets": [
      {
       "expr": "docker_memory_usage{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Network Sum Traffic",
     "type": "heatmap",
     "description": "Received + Transmit",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 333 },
     "targets": [
      {
       "expr": "rate(docker_network_received_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m]) + rate(docker_network_transmit_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "IOps",
     "type": "heatmap",
     "description": "Input + Output (Write + Read)",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 333 },
     "targets": [
      {
       "expr": "rate(docker_io_write_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m]) + rate(docker_io_read_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Count History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers All Count",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 374 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(docker_containers_up_count{hostname=~\"$HostName\"}+docker_containers_down_count{hostname=~\"$HostName\"}) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Containers Down Count",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 387 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(docker_containers_down_count{hostname=~\"$HostName\"}) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    }
   ]
  }
 ]
}